services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:1-9.0
    volumes:
      - ../..:/workspaces:cached
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: sleep infinity
